### ISSUE TITLE
Unable to sign in and update data

### ISSUE THREAD

**Issue by chrsep** [chrsep/Kingfish#13]
Lately, Portal has been unable to fetch any data from Binusmaya due to some changes to the way it logs user in. One of the changes is now the inclusion of a hidden token field on login. 

I released a patch to fix this by fetching the login html first, extract the token out, and use it on the next login request. This works as of last night, but today this fix doesn't seem to work anymore. Fixing this might take some time

**Comment by mstephen77** [comment]
I've tried to mess around by creating a fake request with PHPSESSID, token, and defaultLoginReal intact, and it seems to have no problem at all, unless you do HTTP GET to the login page (https://binusmaya.binus.ac.id/login/index.php) more than once, which in turn would generate a different token...

**Comment by chrsep** [comment]
@mstephen77  Have you tried getting data using the PHPSESSID that you used to login? Like from "https://binusmaya.binus.ac.id/services/ci/index.php/scoring/ViewGrade/getPeriodByBinusianId" ?

My every request seems to fails, maybe there is something wrong with my request header, I'll look into it again later.

**Comment by mstephen77** [comment]
@chrsep: Are you sure you're using a correct Referer in the header? Everything seems fine for me.
![image](https://cloud.githubusercontent.com/assets/22470683/26448956/053454fa-417a-11e7-8d14-c7844d1a3ced.png)

**Comment by chrsep** [comment]
@mstephen77 i did, it works if i login through the browser and copy the PHPSESSID to the request to getPeriodByBinusianId. I am trying to login with my own request to "https://binusmaya.binus.ac.id/login/sys_login.php" like in the screenshot ( i fill the uid and pass while leaving defaultLoginReal empty ). When i use the PHPSESSID from this request, all my request to getPeriodByBinusianId fails.

![image](https://cloud.githubusercontent.com/assets/8491552/26450348/9da32ada-411c-11e7-91cc-8af1912c8f29.png)

Do you know how to get this to work?

**Comment by mstephen77** [comment]
@chrsep: Can you get the response from any URI (ex. "https://binusmaya.binus.ac.id/services/ci/index.php/scoring/ViewGrade/getPeriodByBinusianId") with that PHPSESSID? (I used "Postman" to create requests and view responses) If it's unauthorized then that PHPSESSID is just a session_start() in php which was created when you opened https://binusmaya.binus.ac.id/login/index.php while in reality you haven't been logged in yet. That's probably why your requests to the URI failed.

**Comment by mstephen77** [comment]
![image](https://cloud.githubusercontent.com/assets/22470683/26452578/a2d05e7e-418a-11e7-8bbf-7d08c8b720a8.png)
There, by just opening https://binusmaya.binus.ac.id/login/index.php, as you can see, php already generates a PHPSESSID (That meant a session_start() on PHP, which was done on the backend server). If you create a request using that PHPSESSID, Binusmaya's services would get an error because you're actually not logged in (despite the PHPSESSID)

**Comment by mstephen77** [comment]
>  ( i fill the uid and pass while leaving defaultLoginReal empty )

Oh also worth mentioning that if you did create a request like you stated above, that's probably the problem. Because you need to fill in the captcha (defaultLoginReal) with the result of the captcha, which means it cannot be empty.

**Comment by chrsep** [comment]
@mstephen77 That's what i was afraid of, Binusmaya's captcha used to have a bug, it seems that the captcha will be set to a default value (an empty string) for a given session before https://binusmaya.binus.ac.id/login/captcha.php is called by the session, because of this i could just leave defaultLoginReal empty, and users would get logged in just fine. this is how i bypass the captcha since it was first introduced to keep Portal working.

I am just hoping that this is still the case, and that i am just doing something wrong with my requests. Binusmaya's design decisions do sometimes perplexes me, like the addition of the new token field and captcha, it just seems weird to me to include all of this.

Do you think there might be any other reason why the login request fails?

**Comment by mstephen77** [comment]
@chrsep: OHHH, now everything makes sense. You used to do a POST directly to sys_login.php before, right? Now, with an addition of a token, you're forced to HTTP GET to binusmaya.binus.ac.id/login/index.php, and there, in index.php, it will do a HTTP GET to captcha.php (something along the line of <img src="captcha.php">), which was why your captcha bypass isn't working anymore. But there shouldn't be any problems with your token though nor your request header, so the remaining thing should only be the captcha which is causing you a whole lot problem. xD

**Comment by chrsep** [comment]
@mstephen77 Damn, that might be it, index.php might have triggered something, maybe that's the purpose of the token. I'll try to look into this tomorrow. This captcha really is an unnecessary hurdle, i don't understand why they have to put it there.

**Comment by mstephen77** [comment]
@chrsep: If you could block requests to https://binusmaya.binus.ac.id/login/captcha.php then that would be for the best, since you don't have to change anything else and keep the defaultLoginReal empty, I suppose.

**Comment by chrsep** [comment]
@mstephen77 I just tested it. i think they might have fixed the captcha bug. It's possible that the default value is now randomized so it's probably impossible to keep the defaultLoginReal constant.
 
I've tested this by copying the token that i know works and using it to login on portal while removing the call to index.php. It fails when i try to call with empty defaultLoginReal, so then i opened the login page with the PHPSESSID that i use, look at the captcha image that i get and put the answer into Portal's subsequent request, then it works.

I guess there is no way around the captcha anymore now.

**Comment by mstephen77** [comment]
> copying the token that i know works

@chrsep: Forgive me for being rude, but how do you know that the token works?

**Comment by chrsep** [comment]
@mstephen77 When i first try to fix this, when leaving the defaultLoginReal empty still works, the same token works multiple times, only after some few minutes that all my request fails. I conclude that the tokens are invalidated only after certain length of time, this leads me to create the mechanism to fetch the token. I expect that this is still the case.

Besides, when i try it now, my request only fails the first time when i left the defaultLoginReal empty. On the subsequent requests after i filled the defaultLoginReal with the correct answer, i were able to login, even changing accounts works, they probably doesn't even change the  captcha associated with the PHPSESSID after the first successful login.

**Comment by mstephen77** [comment]
@chrsep: Eh, sorry. Nevermind about that actually. I blocked all requests to captcha.php yet can't still have it empty. You know, might as well put a captcha everytime user needs to login / update... (though it should be possible to use OCR xD)

**Comment by chrsep** [comment]
@mstephen77 I don't think asking user for captcha is good. It would make automating the update impossible, and it's going to be really annoying. I'll probably try to implement a way to automatically answer the captcha, this probably gonna take some time :disappointed:

**Comment by mstephen77** [comment]
@chrsep: If it's possible, could you create the one where it asks the user for captcha first (if it's easier and doesn't take much of your time), since I use this app because of Realm (offline db) instead of Binus Mobile 😂. After all, the captcha will be there only when the user logs in/updates, so imo, no one would really mind.

**Comment by chrsep** [comment]
@mstephen77 hmmm... I suppose you're right, implementing the captcha wouldn't be really hard, and i am kinda a bit busy. It's probably better to implement the captcha temporarily while the OCR is being build. I'll try to implement this tonight.

**Comment by chrsep** [comment]
I've pushed an update yesterday, with the fix in 7a2445. We'll see whether this works reliably in the next couple of days.

**Comment by chrsep** [comment]
Apparently the fix only work on my phone and a few other phone. This is hard for me to debug because my phone successfully login everytime I detected some 30 successful login.... and around 2k failed login attempts. This  is bewildering. @mstephen77 does the captcha works on your phone?

**Comment by chrsep** [comment]
I am currently studying abroad, and i am away from my usual development equipment. This makes developing android app really hard. I also already have to much things to do, so I don't think i can work on this for some time. Hopefully someone can hop in and help with this.

**Comment by mstephen77** [comment]
@chrsep: The latest update from Google Play Store somehow doesn't work for me either. Is it possible for you to fetch the responses after doing a POST to sys_login.php? Because for me, I myself did like this (in C#). That way, if login failed, I'd knew what's wrong (Binusmaya would put it in a div#login_error in its' response).
![image](https://cloud.githubusercontent.com/assets/22470683/26521641/51af927e-4317-11e7-82cd-bfc873df7292.png)

**Comment by chrsep** [comment]
@mstephen77 My phone can log in perfectly, so i can't test it on my phone. I'll release an update to gather this data.

**Comment by chrsep** [comment]
@mstephen77 I got "../login/?error=4" on all failed request. Seems like it's definitely something wrong with the captcha.

**Comment by mstephen77** [comment]
@chrsep There's 2 reason for `../login/?error=4`, the first one is it's really an invalid captcha, or the second one is an invalid token. The first would happen if you do a HTTP GET to the captcha.php before getting token, or in other words, you have to get the index.php before captcha.php (something about PHP's session). The second probability is low, and only happens if you're using old token (because I refresh the token for every HTTP GET to index.php / login error)

**Comment by mstephen77** [comment]
I don't have any problem doing it like this...
![image](https://cloud.githubusercontent.com/assets/22470683/26525282/70f80754-437d-11e7-82a8-613328c441c0.png)
![image](https://cloud.githubusercontent.com/assets/22470683/26525283/79840e86-437d-11e7-92f9-66fe79042e2d.png)

**Comment by chrsep** [comment]
@mstephen77 Have you tried getting the captcha before the getting the token? I don't think the token is tied to the PHPSESSID because i can just copy only the token i got from my browser into my Portal with out copying over the cookie, and the request would still be successful with the new cookie. Here is what i got every time. It's taken directly from Portal's network requests.

![image](https://cloud.githubusercontent.com/assets/8491552/26525469/91b99ea4-431d-11e7-98ae-7d2215146da9.png)

If one of the request returns an unexpected value, all the subsequent request will be cancelled.

I've tried reinstalling Portal with both the play store version and by building from the develop branch here, wiping the data, switching to android guest user. And every single requests are always successful. Switching between multiple Binusmaya accounts also works. All this while always using new token and cookie.

Could you try running Portal from source and capture the request?

**Comment by mstephen77** [comment]
@chrsep The gradle build failed for me, something about failed to import firebase. Tried sniffing the packets sent with Wireshark but it's seemed encoded

**Comment by mstephen77** [comment]
@chrsep Oh, and also, I'm just afraid that when you GET index.php, it would mess with the already GET captcha.php, that's why I set the order to be that way... i don't know though

**Comment by chrsep** [comment]
@mstephen77 The gradle error could be caused by outdated sdk, `firebase-perf` has only been announced yesterday at Google I/O. Have you tried updating your sdk and android studio? If you could get it to work, you could easily inspect all of Portal's data and network request by opening `chrome://inspect/#devices`.

Getting the token before getting the captcha is a bit more complicated, so i'd rather just asked the user about the captcha first, then combine all the other requests in one place.

**Comment by mstephen77** [comment]
@chrsep Which branch is the latest (the one on Google Play Store)?

**Comment by chrsep** [comment]
@mstephen77 it's the analysisUpdate

**Comment by mstephen77** [comment]
@chrsep 'kay so updated everything in Android Studio. Build is fine, but I can't use ADB to debug to my device. 
![image](https://cloud.githubusercontent.com/assets/22470683/26527132/801bb4b2-43b7-11e7-9051-886d8e5e6348.png)
Any idea?

**Comment by chrsep** [comment]
@mstephen77 i forgot about that, i've fixed that in develop but haven't merge it down to analysisUpdate. I've just push the fix to analysisUpdate, try git pull.

**Comment by mstephen77** [comment]
@chrsep Eh nevermind actually. Somehow it worked with Instant Run. Anyway, the request to `sys_login.php` for me has the defaultLoginReal empty despite me filling in the captcha. That's the problem. I don't know why it's empty, though.

**Comment by chrsep** [comment]
@mstephen77 This is a bit frustrating, how come does it work in mine?

![image](https://cloud.githubusercontent.com/assets/8491552/26527414/8c46895a-4359-11e7-9054-1918544e4ad5.png)

I can't fix something that i can't see.

**Comment by mstephen77** [comment]
@chrsep Is there a way with Kotlin to output back to Android Studio? Console.WriteLine, Debug.Log, etc, etc...?

**Comment by chrsep** [comment]
@mstephen77 You could use android's log function. https://developer.android.com/reference/android/util/Log.html.  Just use `Log.d(String, String)`.

**Comment by chrsep** [comment]
@mstephen77 hmm... That's possible, usually Android Studio gives out warning if a certain function is not available in the app's target API though. I'll try to remove that function. And push out update to beta users to test.

**Comment by mstephen77** [comment]
@chrsep Just pulled your recent SyncManager, the captcha is working now. Well, for me, at least. I'll await the update.

**Comment by chrsep** [comment]
@mstephen77 Finally some good news :smile: . Hopefully everything works fine.

**Comment by felixlix45** [comment]
I can confirm that the last update (Google Play Store) is working. Thank You

**Comment by chrsep** [comment]
@felixlix45 Good to hear :smile: , i'll be rolling the update out to everyone and monitor the changes over the next couple of days

**Comment by chrsep** [comment]
Apparently, it seems that the login is failing again, still caused by captcha (`../login/?error=4`). But the root cause teems to be different now, `defaultLoginReal` is still correctly filled.

**Comment by mstephen77** [comment]
@chrsep Yeah, probably because you're trying to use old data (Cookie? Token?) which is why it fails

**Comment by mstephen77** [comment]
@chrsep How to clear Realm saved prefs? Will clearing data do it?

**Comment by chrsep** [comment]
@mstephen77 Yes, clearing the data should do it. I saved the cookie in android's `SharedPreference`, I am not saving the token though. 

I think the fact that Portal works for a while shows that there must be some changes to Binusmaya. Don't know what yet though.

**Comment by mstephen77** [comment]
@chrsep Weird, I could still login just fine using C# and nothing changed from Binusmaya. I think you should refresh the token thing (if you're using the old saved token data).

**Comment by chrsep** [comment]
@mstephen77 Hmmm..... Portal don't reuse the same token, it's probably something wrong with the sequence of the request though. I'll try to move the signin process to it's own file. It seems to be very complicated

**Comment by chrsep** [comment]
Now working again on my devices, and I am slowly rolling out a new update. Seems like there is some problem in handling the cookie, I rewrite the sign in process and cookie handling almost from scratch in 3940045, and now it works. I am sorry for all the trouble.

**Comment by chrsep** [comment]
From what i see, this issue seems to be resolved now, the number of failed login have gone down significantly over the past few days. I'll be closing this now.

@mstephen77 Thanks for your help, it would probably take a lot longer to fix this without your help. :smile:
