### ISSUE TITLE
Subject Name and Time overlaps for Exams

### ISSUE THREAD

**Issue by funAlways** [chrsep/Kingfish#28]
Basically, if the subject name is long enough (e.g. "English for Business Presentation"), it'll overlap with exam schedule time, making it almost unreadable. 
Easy solution would be move the exam time to second line, next to seat and room numbers.

**Comment by chrsep** [comment]
This should be easy enough to implement, the other schedule item probably also have this problem. [item_session](https://github.com/chrsep/Kingfish/blob/master/app/src/main/res/layout/item_sessions.xml) handles the layout for the normal schedule item and [item_jexam](https://github.com/chrsep/Kingfish/blob/master/app/src/main/res/layout/item_jexams.xml) handles the exam items. I haven't got time to work in this yet, anyone can try to implement this though.

**Comment by cviali** [comment]
Aligning journal_exam_shift's baseline in [item_jexams](https://github.com/chrsep/Kingfish/blob/master/app/src/main/res/layout/item_jexams.xml) to journal_exam_chair could work, since both journal_exam_chair and journal_exam_room rarely takes full width of a screen.

**Comment by chrsep** [comment]
I just got time to work with Portal again. Yeah, i think journal_exam_shift baseline should be aligned with journal_exam_chairs's. Might as well moved it to the far left though i think, so it's more consistent with the normal class schedule (the normal class having it's time on the bottom far left).

**Comment by chrsep** [comment]
I'll try to make this change.
