### ISSUE TITLE
Resources tab issue

### ISSUE THREAD

**Issue by TreonS** [chrsep/Kingfish#30]
When i click the resources tab, the portal app force close.

**Comment by TreonS** [comment]
From the code, it do nothing right after the if?

**Comment by TreonS** [comment]
I've updated the newest version and it  works.  Thank you @chersep

**Comment by chrsep** [comment]
Thanks @TreonS, sorry i haven't got time to reply. It was my mistake, the if was useless 🤣, i forgot to change it. I'll close this issue now.
