### ISSUE TITLE
I can't log in to Portal

### ISSUE THREAD

**Issue by Moemoesuna** [chrsep/Kingfish#32]
Help I can't log in to my Portal, I uninstall and reinstall Portal because my Financial is not updating and now I can't log in to Portal

**Comment by Joonath** [comment]
CMIIW, but it seems like the access token of login session is being hidden somewhere (or perhaps they reverted back to their old method) since I didn't see any random alphanumeric value at the address bar.

**Comment by chrsep** [comment]
Hi, sorry for the late response, i haven't got much free time lately. @Joonath It does seems like they revert back to old login method, I've reverted Portal to use the old login method now. @Moemoesuna do you still have problem logging in with the updated version?

**Comment by Moemoesuna** [comment]
Thanks!! It works nicely now. Keep up the good work!
